/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lib;

public class LocalLib {
    public boolean someLibraryMethod() {
        return true;
    }

    public String sayHello() {
        return "Hello from local java library";
    }
}
