/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lib;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LocalLibTest {
    @Test void testSomeLibraryMethod() {
        LocalLib classUnderTest = new LocalLib();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
